### ISSUE TITLE
Error "Transform failed. missing status line"

### ISSUE THREAD

**Issue by jessie-wangjie** [ENCODE-DCC/encoded#1099]
I tried to install the encoded on my local computer, and followed the instructions on the main page, it all works well. But when I try to open the webpage, it shows "Transform failed. missing status line". 
Here is the log:
2016-01-13 11:37:46,707 WARNI [subprocess_middleware.worker][waitress] Retrying: ValueError('missing status line',)
b"\n_stream_readable.js:749\n    throw new Error('Cannot switch to old mode now.');\n          ^\nError: Cannot switch to old mode now.\n    at emitDataEvents (_stream_readable.js:749:11)\n    at Socket.Readable.resume (_stream_readable.js:734:3)\n    at Object.<anonymous> (/data/jwang56/software/encoded-36.0/src/encoded/static/server.js:26:19)\n    at Module._compile (module.js:456:26)\n    at Object.Module._extensions..js (module.js:474:10)\n    at Module.load (module.js:356:32)\n    at Function.Module._load (module.js:312:12)\n    at Function.Module.runMain (module.js:497:10)\n    at startup (node.js:119:16)\n    at node.js:935:3\n"

This error appears since v33. Need help. Thank you.

**Comment by hitz** [comment]
I suspect you have a newer (or perhaps older) version of nodejs; there are still a few things that are not version locked.
Are you running this on MacOSX or Linux?   On my mac am running node v.4.2.0 
(>node --version)

You do have to periodically rebuild the system as you update the source.  Do this:
       > rm -rf node_modules eggs parts bin
        >rm -rf .sass-cache
        >rm -rf src/encoded/static/css

>python3 bootstrap.py --buildout-version 2.4.1 --setuptools-version 18.1
and then bin/buildout 

Thanks for using encoded!

**Comment by jessie-wangjie** [comment]
I fixed the node, and it works! I don't know why my old node version is v0.10.41.Thank you!
