### ISSUE TITLE
Can't spin up instance on my lab's AWS account

### ISSUE THREAD

**Issue by scottx611x** [ENCODE-DCC/encoded#1273]
@hitz, people within my lab are truly excited about using your software so I've been instructed to try to follow your docs and get an instance running on our own AWS account.

I've gotten as far as running: `tail -f /var/log/cloud-init-output.log` as stated in `AWS.rst`, but the cloud init will fail due to my user not having access to your S3 bucket (I believe some db backups are trying to be pulled from there). 

What is most sought after by my lab members is to run our own instance on AWS without any dependance on backup data, your authorization technique, etc.

What would it take for this to happen??? 

I would gladly contribute documentation if it is thought that others would want to do the same in the future.

Also if there is a better method of communication than the issue tracker, please let me know :)

**Comment by hitz** [comment]
Ah, this issue tracker should work, but apparently I didn't see this until now.   
Are you trying to adapt the software to your own project?   Or to see encode data?

**Comment by scottx611x** [comment]
@hitz We're trying to adapt your software to work on our own AWS instance.

**Comment by hitz** [comment]
So you want read-access to encode database backups? and files I can't really grant you that; there is data that is unreleased.    Are you in the Park lab?  Are you trying to set up something for 4D Nucleome?

**Comment by scottx611x** [comment]
@hitz Yep I'm in the ParkLab working with Burak Alver. I believe the idea is to not need to rely on your backups at all. We'd like to be have an instance that is completely independent where we can submit our own data, alter the metadata of submitted biosamples/datasets, and not need to rely on being registered with the encode consortium for the creation of a user account. 

I know you guys have a pretty established codebase, so if this doesn't seem possible or if it would do more harm than good to make these changes please let me know.

Alternatively, if you think that it is doable, if you could point me in the right direction I would gladly try making some changes on my own.

**Comment by hitz** [comment]
OK, that makes more sense.   We DID do this for the clingen group in the cherry lab, although they were using an older fork of the software.   We are currently working on separating out the "snovault" package which would be completely generic, but it's going to take a couple more months at least.
It might help to look at https://github.com/ClinGen/clincoded and diff their cloud-config and other config files.

Here is a laundry list of things you need to change, and you are going to have to know (or learn) a bit about aws and setting up all your permissions and keys.
1) in src/encoded/commands/deploy.py it assumes an IamInstanceProfile called encoded-instance (and also writes some debugging statements that assume an encodedcc.org domain, which clearly you don't have)
2) Similarly, you will need to create an s3 bucket for database (WAL-E) backups.  Ours is s3://encoded-backups-proxy/production 
3) you will have to modify cloud-config.yml (and if you want continious integration, .travis.yml) - probably you want to clone your fork of encoded, and you can change the username/group from "encoded" to whatever you want (whenever we use sudo -u encoded... ) 
I don't think you will need this line at all: - sudo -u encoded bin/aws s3 cp --recursive s3://encoded-conf-prod/.aws .aws, but if you do you will have to have your own bucket and your own .aws creds.
4) You will have to recraft /etc/encoded-apache.conf to fit your site.  Probably this is pretty easy.
5) base.ini has pointers to our buckets and AWS profiles, you will have to replace them with your own, same with production.ini.in and candidate.cfg (2 buckets and a pointer to an external ES server, region-search that is not used for the main metadata app).

That should get you started, although it's probably not an exhuastive list.

**Comment by scottx611x** [comment]
@hitz Great Ben thanks for the info. I'll try this out by the end of the week.

**Comment by j1z0** [comment]
hi @hitz -- Thanks for the tips, went through and got pretty much everything running.

By the way the line

```
sudo -u encoded bin/aws s3 cp --recursive s3://encoded-conf-prod/.aws .aws
```

you did need that... Anyways I'm not very familiar with pyramids, but because we don't have any WAL-E backups to load the database from I wanted to just create the basic schema so I could start with an empty database and then perhaps use the load_test_data function to load some data in there.

I was looking through the dev-server command in hopes that it would tell me where the schema is loaded, but I don't see any schema being loaded into the database.  How do I just load the schema.  I.e. in django you would run `manage.py migrate`.  How to do that for encode?

**Comment by j1z0** [comment]
ok I see now create_tables = True in produciton.ini  :)

**Comment by hitz** [comment]
also you can add fake data in src/encoded/tests/data/inserts -- for the test or development app

**Comment by j1z0** [comment]
@hitz -- this can be closed as we have it all working now
