### ISSUE TITLE
Encyclopedia Image on Firefox is full image size

### ISSUE THREAD

**Issue by detrout** [ENCODE-DCC/encoded#1578]
Hi,

On my system running firefox 45.4.0 on Linux the encyclopedia image src="static/img/classic-image.jpg" goes off the right side of the page

I made it fit properly by adding "width: 100%" to .site-banner-img img I don't know if this affects the rapid release version of firefox. It looks like I have the extend support version installed right now

**Comment by hitz** [comment]
@forresttanaka  does this make any sense to you

**Comment by forresttanaka** [comment]
@hitz, yup, though I’ll need to install Linux in a VM to test it — I don’t see this problem with Firefox Mac. _Doubt_ that’ll be a problem, though I haven’t done that in ages.

**Comment by hitz** [comment]
you can use VMware fusion (free download from Stanford)

**Comment by detrout** [comment]
Works fine with Firefox 52.3.0 (64-bit) which is the new ESR, so this probably is no longer relevant
