### ISSUE TITLE
submitter sign-in 

### ISSUE THREAD

**Issue by Parul-Kudtarkar** [ENCODE-DCC/encoded#1917]
Followed instructions to setup test login [1237](https://github.com/ENCODE-DCC/encoded/issues/1237)
when I reload database with dev-server, I get 504 gateway timeout error
errors on loading
INFO:encoded:Loaded 24 of 24 file (phase 2). CREATED: 0, UPDATED: 24, SKIPPED: 0, ERRORS: 0
Started. ^C to exit.
LOG:  autovacuum launcher started
LOG:  unexpected EOF on client connection with an open transaction
LOG:  unexpected EOF on client connection with an open transaction
.....

-------
user.json file has
    {
        "email": "parulbioinf@gmail.com",
        "fax": "000-000-0000",
        "first_name": "Parul",
        "google": "google",
        "job_title": "PI",
        "lab": "Roadmap Epigenomics, Baylor",
        "last_name": "Kudtarkar",
        "phone1": "000-000-0000",
        "phone2": "000-000-0000",
        "skype": "skype",
        "submits_for": [
            "Roadmap Epigenomics, Baylor"
        ],
        "timezone": "US/Pacific",
        "uuid": "5efa3aa8-9c74-418c-83e4-9b97b6b5af29"
    },

Thanks!

**Comment by Parul-Kudtarkar** [comment]
Any feedback? Thank you!

**Comment by Bek** [comment]
Can you paste all of the error messages?

**Comment by Parul-Kudtarkar** [comment]
@Bek 


2017-07-05 18:49:58,287 INFO  [requests.packages.urllib3.connectionpool][waitress] Starting new HTTPS connection (1): encode.auth0.com
> /Users/parulkudtarkar/Desktop/Encode/encoded/src/encoded/auth0.py(84)unauthenticated_userid()
-> if user_info['email_verified'] == True:
(Pdb) 2017-07-05 18:50:02,067 INFO  [elasticsearch][listener] GET http://localhost:9200/snovault/meta/indexing [status:200 request:0.007s]
2017-07-05 18:51:02,096 INFO  [elasticsearch][listener] GET http://localhost:9200/snovault/meta/indexing [status:200 request:0.003s]
2017-07-05 18:52:02,120 INFO  [elasticsearch][listener] GET http://localhost:9200/snovault/meta/indexing [status:200 request:0.009s]


On the web-browser
504 Gateway Time-out

**Comment by Bek** [comment]
Is this happening when you are trying to sign in via the sign in window after 'dev-server' have finished loading the data, and bin/pserve command finished indexing the data?

**Comment by Parul-Kudtarkar** [comment]
Yes, this happens after I "sign in via the sign in window after 'dev-server' have finished loading the data, and bin/pserve command finished indexing the data"

**Comment by Bek** [comment]
Ok, we are going to rule out issues one by one. Did you just open this email account?

**Comment by Parul-Kudtarkar** [comment]
@Bek thanks, I have this email account for few years now.

**Comment by Bek** [comment]
On the terminal screen that shows the last error, please type 'p user_info' and paste the result here please.

**Comment by Parul-Kudtarkar** [comment]
last error: 2017-07-06 11:09:52,758 INFO  [requests.packages.urllib3.connectionpool][waitress] Starting new HTTPS connection (1): encode.auth0.com
> /Users/parulkudtarkar/Desktop/Encode/encoded/src/encoded/auth0.py(84)unauthenticated_userid()
-> if user_info['email_verified'] == True:
-----
(Pdb) p user_info
{'error_description': 'invalid credentials', 'error': 'unauthorized'}

**Comment by Bek** [comment]
It appears that Google is not authenticating your gmail account parulbioinf@gmail.com

**Comment by Parul-Kudtarkar** [comment]
@Bek my auth0 was trying to authenticate with ENCODE changed https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/auth0.py#L72 to ours. 
Thanks for the help!
