### ISSUE TITLE
adding static pages

### ISSUE THREAD

**Issue by Parul-Kudtarkar** [ENCODE-DCC/encoded#1927]
Any pointers on adding static pages such as 
-https://www.encodeproject.org/help/getting-started/
-https://www.encodeproject.org/help/contacts/

and so on, do they reside in encoded/src/encoded/static/components directory?

Thanks!

**Comment by Bek** [comment]
Did you find out how to add static pages?

**Comment by Parul-Kudtarkar** [comment]
yes via. the pages link! However, I am not able to change the navigation links (via. app.js) in this case remove links. I do the following:
-comment lines 
-followed by building dev bundles

Is there any other place this change should be reflected. Sorry I am still getting my way around the codebase.

**Comment by forresttanaka** [comment]
Do you mean the main navigation bar, that currently shows “Data,” “Encyclopedia," etc.?

That’s handled with the `portal.global_sections` array defined in the global space of app.js. But it sounds like you were there already. Changing any of the objects directly in this array should change the main navigation, and changing any subobjects should change the items that appear in the main navigation drop-downs.

Then you rebuild with `$ npm run dev` or `$ npm run build`, and reloading the site should show these changes.

**Comment by Parul-Kudtarkar** [comment]
@forresttanaka yes, I the main navigation bar with Data and Encyclopedia etc.
 
Indeed, I was changing the portal.global_sections and than building the npm run build - reload the site. 
i.e. // { id: 'ontologies', title: 'Ontologies', url: '/help/getting-started/#Ontologies' }, 
// { id: 'fileformats', title: 'File formats', url: '/help/file-formats/' }, 
However, clicking on the dropdown menu on the browser  there after would return something like
https://www.encodeproject.org/#

**Comment by Parul-Kudtarkar** [comment]
@Bek @forresttanaka thanks for the help. Resolved, there was a typo
