### ISSUE TITLE
purpose of peak_metadata in batch_download.py

### ISSUE THREAD

**Issue by Parul-Kudtarkar** [ENCODE-DCC/encoded#2040]
Hi,

What is the purpose of peak_metadata function in batch_download.py 
https://github.com/ENCODE-DCC/encoded/blob/4d5bf217975449aa596c9f2ca97b29372364816d/src/encoded/batch_download.py#L172

Thanks!
Parul Kudtarkar

**Comment by Parul-Kudtarkar** [comment]
Any advise on the question above?

**Comment by Bek** [comment]
it supports the download feature on search pages: https://www.encodeproject.org/search/?type=Experiment&assay_slims=Transcription&assay_title=RNA+microarray

**Comment by Parul-Kudtarkar** [comment]
@Bek Thanks!
