### ISSUE TITLE
indexing of each chromosome/scaffolds

### ISSUE THREAD

**Issue by Parul-Kudtarkar** [ENCODE-DCC/encoded#2046]
Hi,

I have couple of queries, 
1. What function/script initiates "peaks" in a separate index per chromosome? 

On server 1, indexing for each chromosome/scaffolds works 
-----------
curl 'localhost:9200/_cat/indices?v'
health status index                   pri rep docs.count docs.deleted store.size pri.store.size 
yellow open   chr7                      1   1   10075762      1927664    433.4mb        433.4mb 
yellow open   chrun_ki270515v1          1   1        277           11     30.1kb         30.1kb 
yellow open   chr22_ki270735v1_random   1   1        755            0     39.7kb         39.7kb 
yellow open   chrun_ki270754v1          1   1        206            2     19.1kb         19.1kb 
yellow open   chrun_gl000218v1          1   1        557           15     38.2kb         38.2kb 
 --------
However, recently it isn't working for new server that I spawned.
New server ->
$ curl 'localhost:9200/_cat/indices?v'
health status index         pri rep docs.count docs.deleted store.size pri.store.size 
yellow open   annotations     1   1      80275          645     62.3mb         62.3mb 
yellow open   vis_composite   1   1          1            0     38.2kb         38.2kb 
yellow open   snovault        5   1         55            0      5.5mb          5.5mb 
-------

2. Are there other scripts besides peak_indexer.py, region_search.py that are responsible for peak indexing of bed files?

Thank you,
Parul Kudtarkar

**Comment by Parul-Kudtarkar** [comment]
My guess is mapping/indexing for hg19 or GRCh38 is not initiated. is there a script initiate indexing for assemblies?

**Comment by Bek** [comment]
Apache runs the wsgi app that is responsible for peak indexing: https://github.com/ENCODE-DCC/encoded/blob/master/etc/encoded-apache.conf#L21
Errors due to missing mapping should show up in Apache/Elasticsearch error logs.

**Comment by Parul-Kudtarkar** [comment]
Thanks @Bek 
The apache error log has 

[:error] [pid 1540:tid 139707617904384] WARNING [elasticsearch][Dummy-1] GET /chr18/hg19/_search?size=99999 [status:404 request:0.006s]

I think this is because index isn't been created per chromosome. 

In production.ini files the snp_search_server is set to localhost:9200 and the port 9200 is open

Any idea to further debug and fix this?

--

status | 200
-- | --
name | "Kiber the Cruel"
cluster_name | "elasticsearch"
version |  
number | "1.7.6"
build_hash | "c730b59357f8ebc555286794dcd90b3411f517c9"
build_timestamp | "2016-11-18T15:21:16Z"
build_snapshot | false
lucene_version | "4.10.4"
tagline | "You Know, for Search"

**Comment by Bek** [comment]
Indexes are created in the following function: 
https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/peak_indexer.py#L114

Try putting some print statements in the function and observe in the error.log whether .bed files are being processed and indexes are being created.

**Comment by Parul-Kudtarkar** [comment]
@Bek This helps, thank you so much.

**Comment by Parul-Kudtarkar** [comment]
@Bek looks like the files aren't getting indexed
I inserted 
log.warn(peak_results) 

here https://github.com/ENCODE-DCC/encoded/blob/9ab6e1089116153d5c4e5a05830153692f9425f6/src/encoded/region_search.py#L336

gives - WARNING [encoded.region_search][Dummy-1] {'hits': {'hits': [], 'total': 0, 'max_score': None}, '_shards': {'failed': 0, 'total': 1, 'successful': 1}, 'took': 160, 'timed_out': False}

**Comment by Bek** [comment]
Try debugging the peak_indexer.py code that is responsible for indexing .bed files.

**Comment by Parul-Kudtarkar** [comment]
@Bek thanks! I was able to resolve the issue of indexing  .bed files by logging peak_indexer.py.
