### ISSUE TITLE
Re-indexing

### ISSUE THREAD

**Issue by Parul-Kudtarkar** [ENCODE-DCC/encoded#2114]
From the doc -
curl -XDELETE 'http://localhost:9200/encoded/' will delete the entire index along with the mapping information for schema objects.

Gives 

error | "IndexMissingException[[encoded] missing]"
-- | --
status | 404

----

I believe rebooting the  cloud instance should initiate re-indexing, however  it does not. Please advise on possible solution.

Thanks,
Parul

**Comment by caseylitton** [comment]
Hey Parul,

I get the same error when running "curl -XDELETE 'http://localhost:9200/encoded/'".  Those instructions are out of date.

I have not tested this but I hope it helps.

'encoded' has changed to 'snovault',
curl -XDELETE 'http://localhost:9200/snovault'

You may need to run the mapping script,
bin/create-mapping production.ini

Then restart apache or reboot the instance,
sudo service apache2 restart

Thanks,
Casey

**Comment by Parul-Kudtarkar** [comment]
@caseylitton thank you! 
We can now reindex
snovault |  
-- | --
aliases | {}
mappings | {…}
settings | {…}
warmers | {}

Best Regards,
Parul
PS. Our resource - https://www.t2depigenome.org is based on ENCODE project software. We sincerely appreciate your help!

**Comment by caseylitton** [comment]
Awesome!  Glad I could help.  

FYI:  We've updated to elastic search 5 in our snovault and encoded master branches.  The port number will changed from 9200 to 9201 along with other changes.  So be aware if you stay up-to-date with our master branches.

**Comment by Parul-Kudtarkar** [comment]
Thanks you very much, @caseylitton 
Does this require changing the python scripts or simply changing the *.ini files should suffice?
