### ISSUE TITLE
mod-wsgi crashing during data upload

### ISSUE THREAD

**Issue by Parul-Kudtarkar** [ENCODE-DCC/encoded#2245]
Hi developers,

Our portal is based off encode code base, recently we got following error during data upload -
Script timed out before returning headers: wsgi
I was wondering if you have encountered the mod-wsgi crashing during data upload? Do you have different wsgi.conf for the server that handles data-upload and indexing?

Thank you for your help in advance!
Parul

**Comment by hitz** [comment]
@Parul-Kudtarkar thanks for the message.    Not sure what script you are using for data upload?  Are you POSTing remotely or using something like loadxl.py (script run on the server locally).
We don't have a wsgi.conf specifically.... do you mean apache.conf in /etc/?   That probably has some stuff you don't need.
We also run everything though an nginx proxy, but not sure that's relevant.

Sometimes you can run methods remotely that go for >5 minutes or whatever your apache timeout is, I think that will cause that kind of error.

**Comment by Parul-Kudtarkar** [comment]
@hitz thanks for helping with the issue.
For data upload our data manger uses Gsubmitter(POSTing remotely). Indeed, these uploads can take over 5 minutes, that is the default time in apache conf.

Thank you very much,
Parul Kudtarkar

**Comment by Parul-Kudtarkar** [comment]
@hitz They are uploading files from our local server. I  think increasing apache2 timeout is a quick strategy for us to resolve this issue. Thank you very much!
