### ISSUE TITLE
Unable to adding/edit metadata via. UI in cluster ES mode

### ISSUE THREAD

**Issue by Parul-Kudtarkar** [ENCODE-DCC/encoded#2268]
Hi developers,

I cannot edit metadata via. UI 
------
Error:  {"@type":["HTTPServiceUnavailable","Error"],"description":"The server is currently unavailable. Please try again at a later time.","code":503,"status":"error","title":"Service Unavailable"}
The server is currently unavailable. Please try again at a later time. 
------

Thanks!
Parul

**Comment by hitz** [comment]
look in apache error logs.   Can you edit via script?

**Comment by Parul-Kudtarkar** [comment]
@hitz thanks! 
No related error messages in the log and unfortunately my access key has changed every since - that won't let me edit on server via. UI.

**Comment by Parul-Kudtarkar** [comment]
Same error via. script
Annotation: TSTSR037617 Status: proposed
ANNOTATION
/annotations/TSTSR037617/ has status proposed
UPDATING: Annotation /annotations/TSTSR037617/ with status proposed is now released with date 2018-06-01
PATCH failure.  Response = {"description": "The server is currently unavailable. Please try again at a later time.", "@type": ["HTTPServiceUnavailable", "Error"], "code": 503, "title": "Service Unavailable", "status": "error"}
FILE
/files/TSTFF975294/ has status uploading
UPDATING: File /files/TSTFF975294/ with status uploading is now released
PATCH failure.  Response = {"code": 503, "title": "Service Unavailable", "description": "The server is currently unavailable. Please try again at a later time.", "status": "error", "@type": ["HTTPServiceUnavailable", "Error"]}

**Comment by hitz** [comment]
are you using http instead of https?

**Comment by Parul-Kudtarkar** [comment]
Allowing read/write operations i.e.
 sudo pg_ctlcluster 9.3 main promote
Solved the issue. Thanks much for the help!
