### ISSUE TITLE
Initial Indexing

### ISSUE THREAD

**Issue by Parul-Kudtarkar** [ENCODE-DCC/encoded#2333]
Hi Developers, 
A few questions regarding initial indexing 
1. Almost 99.99% initial indexing takes 12 hours after which it pauses and is taking forever, in past if it was a troubled uuid initial indexing would still proceed and completed with _indexer status = waiting. Apache logs are not useful here. Not sure what's happening. Would restarting apache start indexing from the beginning - I doubt it would. Appreciate any thoughts/comments 
2. If I may ask how long does it take for encode's initial indexing? 

Thank you very much!
Parul

**Comment by hitz** [comment]
Our indexing for 1M objects currently takes about 4 hours on a 36p machine with 16 mp indexer threads dedicated.
