### ISSUE TITLE
GEO Accessions as part of experimental metadata download

### ISSUE THREAD

**Issue by Fnyasimi** [ENCODE-DCC/encoded#3304]
Hi,
I am kindly asking is there a way of getting the GEO accessions as part of the metadata when downloading a batch of multiple experiments.

I have a large list of GEO accessions for human TF Chip-Seq experiments and I am interested in finding those that have not been curated and deposited to the ENCODE database. Having this list of GEO accessions for the batch experiments I am using from the database will be helpful to sort things out.

I would really appreciate assistance on this issue.

**Comment by hitz** [comment]
Oh sorry I missed this message.   Probably what you want to do is make a report for the experiments you download and you can add "external resources" as a column (field=dbxrefs)
Example: https://www.encodeproject.org/report/?type=Experiment&internal_tags=SESCC&assay_title!=Control%20ChIP-seq&biosample_ontology.term_name=smooth%20muscle%20cell&field=%40id&field=accession&field=assay_term_name&field=assay_title&field=target.label&field=biosample_summary&field=dbxrefs

We will consider adding dbxrefs to metadata.tsv as well.

**Comment by Fnyasimi** [comment]
Thank you @hitz for the assistance this is really helpful.
