### ISSUE TITLE
how to login in test setup?

### ISSUE THREAD

**Issue by bsr203** [ENCODE-DCC/encoded#848]
Hi,

I was just testing it locally, and not sure how to login. Using my gmail account, persona verified it, but got error.

```
Login failure
Access is restricted to ENCODE consortium members.

Request an account
```

thanks,
bsr

**Comment by nikhilRP** [comment]
@bsr203 Please look at the test data over here - https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/tests/data/inserts/user.json

Change one of the user email to your persona email to login.

Persona audience is configured in the line - https://github.com/ENCODE-DCC/encoded/blob/master/base.ini#L29
If you started the test server locally you can add "localhost:800" to the list.

**Comment by bsr203** [comment]
thanks @nikhilRP worked great.
